Update branding and copyrights
FSHSchool/site pull request #102
Opened 2024-09-09 15:47 UTC by mint-thompson

Remove MITRE logo from header.

Remove MITRE section from about page. Add HL7 section to about page. Change copyright to HL7. Change maintainers to HL7 community.

2024-09-11 20:09 UTC, jafeltra approved these changes

2024-09-11 20:09 UTC, jafeltra commented on README.md
> -3. Add and edit content, refferring to the [Hugo documentation](https://gohugo.io/documentation/)
Lol wooo! 🎉

2024-09-12 12:40 UTC, cmoesel requested changes
This is looking good. I found a couple of things that I think we should fix before merging:

1. The HL7 logo on the About page is too small (see individual comment below).
2. The footer still contains the PRS statement. That should be removed (see screenshot below).

![CleanShot 2024-09-12 at 08 38 53@2x](https://github.com/user-attachments/assets/e2f912aa-95ad-4a9c-886e-f7bc580e83af)

2024-09-12 12:40 UTC, cmoesel commented on static/hl7-logo-header.png
This HL7 logo looks funny next to the larger logos on the About page: 
![CleanShot 2024-09-12 at 08 32 51@2x](https://github.com/user-attachments/assets/4c2b1ec7-74f6-48f5-b5db-ddef587a9230)

I found a bigger version that I think would look better: https://fire.ly/wp-content/uploads/2020/11/HL7_int_01.png.webp

![Bigger HL7 Logo](https://fire.ly/wp-content/uploads/2020/11/HL7_int_01.png.webp)

2024-09-12 13:46 UTC, mint-thompson commented on static/hl7-logo-header.png
Thank you for finding this bigger logo! It definitely looks much better alongside the other two. I've updated the PR to use it.

2024-09-12 15:12 UTC, cmoesel approved these changes
Looks good. Thank you, Mint!

2024-09-12 15:42 UTC, jafeltra approved these changes

2024-09-12 17:54 UTC, merged